Projects/InventoryManagementSystem/InventoryManagementSystem/Models/Purchase.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int id { get; set; }
        public string Purchase_prod { get; set; }
        public string Purchase_qnty { get; set; }
        public System.DateTime Purchase_date { get; set; }
    }
}

Projects/InventoryManagementSystem/InventoryManagementSystem/Controllers/PurchaseController.cs
using InventoryManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventoryManagementSystem.Controllers
{
    public class PurchaseController : Controller
    {
        Inventory_Management_SystemEntities db = new Inventory_Management_SystemEntities();

        // GET: Purchase
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult DisplayPurchase()
        {
            List<Purchase> list = db.Purchase.OrderByDescending(x => x.id).ToList();
            return View(list);
        }

        [HttpGet]
        public ActionResult PurchaseProduct()
        {
            List<string> list = db.Products.Select(x => x.Product_name).ToList();
            ViewBag.ProductName = new SelectList(list);
            return View();
        }

        [HttpPost]
        public ActionResult PurchaseProduct(Purchase pur)
        {
            db.Purchase.Add(pur);
            db.SaveChanges();
            return RedirectToAction("DisplayPurchase");
        }

        [HttpGet]
        public ActionResult DeleteProduct(int id)
        {
            Purchase p = db.Purchase.Where(x => x.id == id).SingleOrDefault();
            return View(p);
        }

        [HttpPost]
        public ActionResult DeleteProduct(int id, Purchase purchase)
        {
            Purchase p = db.Purchase.Where(x => x.id == id).SingleOrDefault();
            db.Purchase.Remove(p);
            db.SaveChanges();
            return RedirectToAction("DisplayPurchase");
        }





        [HttpGet]
        public ActionResult Detail(int id)
        {
            // Retrieve the purchase from the Purchases table based on the provided id
            Purchase purchase = db.Purchase.Find(id);

            if (purchase != null)
            {
                return View(purchase);
            }
            else
            {
                // Handle the case where the purchase with the given id is not found
                return HttpNotFound(); // You can customize this based on your needs
            }
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            Purchase p = (Purchase)db.Purchase.Where(x => x.id == id).SingleOrDefault();
            List<string> list = db.Products.Select(x => x.Product_name).ToList();
            ViewBag.ProductName = new SelectList(list);
            return View(p);
        }


        [HttpPost]
        public ActionResult Edit(int id, Purchase pur)
        {
            Purchase p = db.Purchase.Where(x => x.id == id).SingleOrDefault();
            p.Purchase_date = pur.Purchase_date;
            p.Purchase_prod = pur.Purchase_prod;
            p.Purchase_qnty = pur.Purchase_qnty;
            db.SaveChanges();
            return RedirectToAction("DisplayPurchase");
        }

    }
}

Projects/InventoryManagementSystem/InventoryManagementSystem/Views/Purchase/DeleteProduct.cshtml
@model InventoryManagementSystem.Models.Purchase

@{
    ViewBag.Title = "DeleteProduct";
}

<h2 class="text-center">Delete Product</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Purchase</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Purchase Product")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Purchase_prod)
        </dd>

        <dt>
            @Html.DisplayName("Purchase Quantity")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Purchase_qnty)
        </dd>

        <dt>
            @Html.DisplayName("Purchase Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Purchase_date)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="submit" value="Delete" class="btn btn-danger" />
    @Html.ActionLink("Cancel", "DisplayPurchase", "Purchase", new { @class = "btn btn-primary" })
</div>
    }
</div>

Projects/InventoryManagementSystem/InventoryManagementSystem/Views/Purchase/Detail.cshtml
@model InventoryManagementSystem.Models.Purchase

@{
    ViewBag.Title = "Detail";
}

<h2 class="text-center">Details</h2>

<div>
    <h4>Purchase</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Purchase Product")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Purchase_prod)
        </dd>

        <dt>
            @Html.DisplayName("Purchase Quantity")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Purchase_qnty)
        </dd>

        <dt>
            @Html.DisplayName("Purchase Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Purchase_date)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "PurchaseProduct", "Purchase", new { id = Model.id }, new { @class = "btn btn-primary" })
    @Html.ActionLink("Cancel", "DisplayPurchase", "Purchase", new { @class = "btn btn-danger" })
</p>

Projects/InventoryManagementSystem/InventoryManagementSystem/Views/Purchase/DisplayPurchase.cshtml
@model IEnumerable<InventoryManagementSystem.Models.Purchase>

@{
    ViewBag.Title = "DisplayPurchase";
}

<h2 class="text-center">Display Purchase</h2>

<p>
    @Html.ActionLink("Create New", "PurchaseProduct", "Purchase", new { }, new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Purchase Product")
        </th>
        <th>
            @Html.DisplayName("Purchase Quantity")
        </th>
        <th>
            @Html.DisplayName("Purchase Date")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Purchase_prod)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Purchase_qnty)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Purchase_date)
    </td>
    <td>

        @Html.ActionLink("Edit", "Edit", "Purchase", new { id = item.id }, new { @class = "btn btn-primary" })
        @Html.ActionLink("Details", "Detail", "Purchase", new { id = item.id }, new { @class = "btn btn-success" })
        @Html.ActionLink("Delete", "DeleteProduct", "Purchase", new { id = item.id }, new { @class = "btn btn-danger" })
        
    </td>

</tr>
}

</table>

Projects/InventoryManagementSystem/InventoryManagementSystem/Views/Purchase/Edit.cshtml
@model InventoryManagementSystem.Models.Purchase

@{
    ViewBag.Title = "Edit";
}


@section Scripts {
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.13.2.min.js"></script>
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

    <script type="text/javascript">
        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                dateFormat: "dd/m/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0",
            })
    </script>

}

<h2 class="text-center">Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Update Purchase Record</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Product Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Purchase_prod, ViewBag.ProductName as SelectList, "Select Product", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Purchase_prod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Product Quantity", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Purchase_qnty, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Purchase_qnty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Purchase Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Purchase_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Purchase_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-primary" />
                @Html.ActionLink("Cancel", "DisplayPurchase", "Purchase", new { }, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}

Projects/InventoryManagementSystem/InventoryManagementSystem/Views/Purchase/PurchaseProduct.cshtml
@model InventoryManagementSystem.Models.Purchase

@{
    ViewBag.Title = "PurchaseProduct";
}

@section Scripts {
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.13.2.min.js"></script>
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

    <script type ="text/javascript">
        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                dateFormat: "dd/m/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0",
        })
    </script>
    
}


<h2 class="text-center">Purchase Product</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Purchase</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Product Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Purchase_prod, ViewBag.ProductName as SelectList, "Select Product", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Purchase_prod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Product Quantity", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Purchase_qnty, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Purchase_qnty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Purchase Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Purchase_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Purchase_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
                @Html.ActionLink("Cancel", "DisplayPurchase", "Purchase", new { }, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}